/*
 ******************************************************************************
 * @file    finite_state_machine_ucf.c
 * @author  Sensors Software Solution Team
 * @brief   This file show how to use an ".ucf" file generated by
 *          Unico / Unicleo software tool.
 *
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * This example was developed using the following STMicroelectronics
 * evaluation boards:
 *
 * - NUCLEO_F411RE + X_NUCLEO_IKS01A3
 *
 * and STM32CubeMX tool with STM32CubeF4 MCU Package
 *
 * Used interfaces:
 *
 *
 * NUCLEO_STM32F411RE + X_NUCLEO_IKS01A3 - Host side: UART(COM) to USB bridge
 *                                       - I2C(Default)
 *
 * If you need to run this example on a different hardware platform a
 * modification of the functions: `platform_write`, `platform_read`,
 * `tx_com` and is required.
 *
 */

/* Includes ------------------------------------------------------------------*/
#include <string.h>
#include <stdio.h>
#include "stm32f4xx_hal.h"
#include <lsm6dso_reg.h>
#include "gpio.h"
#include "i2c.h"
#include "usart.h"

/*
 * Below an ".ucf" file generated with Unico / Unicleo software tool (with
 * some comments) where a wake-up program is configued on FSM.
 * The purpose of this example is to show how extract the device
 * configuration from this file and integrate it with platform independent
 * driver API:
 *
 *   --->  Filename: wakeup.ucf <----
 *
 * STEVAL-MKI196V1 (LSM6DSO)
 * Ac 5F 02 // Routing of embedded functions event on INT1.
 * Ac 01 80 // Embedded functions configuration registers.
 * Ac 04 00
 * Ac 05 00
 * Ac 5F 4B // Finite State Machine ODR @  26 Hz.
 * Ac 46 01 // FSM1 enable / FSM2 - FSM8 disabled
 * Ac 47 00 // FSM9 - FSM16 disabled
 * Ac 0A 00
 * Ac 0B 01 // Routing of FSM1 interrupt event on INT1.
 * Ac 0C 00
 * Ac 0E 00
 * Ac 0F 00
 * Ac 10 00
 * Ac 17 40 // Enable Write from the selected advanced features dedicated page
 * Ac 02 11 // Select embedded advanced features page 1
 * Ac 08 7A // Page address register [7Ah - FSM_LC_TIMEOUT_L]
 * Ac 09 00 // Reset to register [7Ah - FSM_LC_TIMEOUT_L]
 * Ac 09 00 // Reset to register [7Bh - FSM_LC_TIMEOUT_H]
 * Ac 09 01 // Write Number of FSM programs [7Ch - FSM_PROGRAMS]
 * Ac 09 01 // Dummy write [7Dh - autoincrement register address]
 * Ac 09 00 // Set FSM start address low register [7Eh - FSM_START_ADD_L]
 * Ac 09 04 // Set FSM start address high register [7Fh - FSM_START_ADD_H]
 * Ac 02 41 // Select page to writing programa
 * Ac 08 00 // Select page address to writing programa
 * Ac 09 50 // Start write program Wakeup
 * Ac 09 40
 * Ac 09 12
 * Ac 09 00
 * Ac 09 0C
 * Ac 09 00
 * Ac 09 00
 * Ac 09 3C
 * Ac 09 66
 * Ac 09 2A
 * Ac 09 02
 * Ac 09 00
 * Ac 09 41
 * Ac 09 75
 * Ac 09 10
 * Ac 09 10
 * Ac 09 22
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 00
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00
 * Ac 09 06
 * Ac 09 00 // Last program write program Wakeup
 * Ac 04 00
 * Ac 05 01 // Enable Finite State Machine (FSM) feature.
 * Ac 17 80 // Embedded Functions interrupt request latched
 * Ac 02 01 // Select embedded advanced features page 0
 * Ac 01 00 // Come back to user register
 * Ac 02 3F
 * Ac 07 00
 * Ac 08 00
 * Ac 09 00
 * Ac 0A 00
 * Ac 0B 00
 * Ac 0C 00
 * Ac 0D 00
 * Ac 0E 00
 * Ac 10 20 // FS 2g, ODR = 26 Hz
 * Ac 11 00
 * Ac 12 04
 * Ac 13 00
 * Ac 14 00
 * Ac 15 00
 * Ac 16 00
 * Ac 17 00
 * Ac 18 E0
 * Ac 19 00
 * Ac 56 00
 * Ac 57 00
 * Ac 58 00
 * Ac 59 00
 * Ac 5A 00
 * Ac 5B 00
 * Ac 5C 00
 * Ac 5D 00
 * Ac 5E 02 // Routing of embedded functions event on INT1.
 * Ac 5F 00
 * Ac 6F 00
 * Ac 70 00
 * Ac 71 00
 * Ac 72 00
 * Ac 73 00
 * Ac 74 00
 * Ac 75 00
 *
 *   ---> End File <---
 *
 */

/* Program: wakeup [ array created from ".ucf" file]*/
const uint8_t lsm6so_prg_wakeup[] = {
      0x50, 0x40, 0x12, 0x00, 0x0C, 0x00, 0x00, 0x3C, 0x66, 0x2A, 0x02, 0x00,
      0x41, 0x75, 0x10, 0x10, 0x22, 0x00, 0x00, 0x00, 0x06, 0x00, 0x06, 0x00,
      0x00, 0x00, 0x06, 0x00, 0x06, 0x00, 0x00, 0x00, 0x06, 0x00, 0x06, 0x00,
      0x00, 0x00, 0x06, 0x00, 0x06, 0x00, 0x00, 0x00, 0x06, 0x00, 0x06, 0x00,
      0x00, 0x00, 0x06, 0x00, 0x06, 0x00, 0x00, 0x00, 0x06, 0x00, 0x06, 0x00,
      0x00, 0x00, 0x06, 0x00, 0x06, 0x00, 0x00, 0x00, 0x06, 0x00, 0x06, 0x00,
      0x00, 0x00, 0x06, 0x00, 0x06, 0x00, 0x00, 0x00, 0x06, 0x00, 0x06, 0x00,
      0x00, 0x00, 0x06, 0x00, 0x06, 0x00, 0x00, 0x00, 0x06, 0x00, 0x06, 0x00,
      0x00, 0x00, 0x06, 0x00, 0x06, 0x00, 0x00, 0x00, 0x06, 0x00, 0x06, 0x00,
    };


/* Private macro -------------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/
static uint8_t whoamI, rst;
static uint8_t tx_buffer[1000];

/* Extern variables ----------------------------------------------------------*/

/* Private functions ---------------------------------------------------------*/

/*
 *   WARNING:
 *   Functions declare in this section are defined at the end of this file
 *   and are strictly related to the hardware platform used.
 *
 */
static int32_t platform_write(void *handle, uint8_t reg, uint8_t *bufp,
                              uint16_t len);
static int32_t platform_read(void *handle, uint8_t reg, uint8_t *bufp,
                             uint16_t len);

static void tx_com( uint8_t *tx_buffer, uint16_t len );

/* Main Example --------------------------------------------------------------*/
void lsm6dso_fsm_ucf(void)
{
  /* Variable declaration */
  stmdev_ctx_t              dev_ctx;
  lsm6dso_pin_int1_route_t   pin_int1_route;
  lsm6dso_emb_fsm_enable_t   fsm_enable;
  lsm6dso_all_sources_t      status;
  uint16_t                   fsm_addr;

  /* Initialize mems driver interface */
  dev_ctx.write_reg = platform_write;
  dev_ctx.read_reg  = platform_read;
  dev_ctx.handle    = &hi2c1;

  /* Check device ID */
  lsm6dso_device_id_get(&dev_ctx, &whoamI);
  if (whoamI != LSM6DSO_ID)
    while(1);

  /* Restore default configuration (not FSM) */
  lsm6dso_reset_set(&dev_ctx, PROPERTY_ENABLE);
  do {
    lsm6dso_reset_get(&dev_ctx, &rst);
  } while (rst);

  /* Disable I3C interface */
  lsm6dso_i3c_disable_set(&dev_ctx, LSM6DSO_I3C_DISABLE);

  /* Enable Block Data Update */
  lsm6dso_block_data_update_set(&dev_ctx, PROPERTY_ENABLE);

  /* Set full scale */
  lsm6dso_xl_full_scale_set(&dev_ctx, LSM6DSO_2g);
  //lsm6dso_gy_full_scale_set(&dev_ctx, LSM6DSO_2000dps); /*gyro not used*/

  /* Route signals on interrupt pin 1 */
  lsm6dso_pin_int1_route_get(&dev_ctx, &pin_int1_route);
  pin_int1_route.md1_cfg.int1_emb_func              = PROPERTY_ENABLE;
  pin_int1_route.fsm_int1_a.int1_fsm1               = PROPERTY_ENABLE;
  lsm6dso_pin_int1_route_set(&dev_ctx, &pin_int1_route);

  /* Configure interrupt pin mode notification */
  lsm6dso_int_notification_set(&dev_ctx, LSM6DSO_BASE_PULSED_EMB_LATCHED);

  /*
   * Start Finite State Machine configuration
   */

  /* Reset/Init Long Counter from FSM_LC_TIMEOUT_L / H */
  lsm6dso_long_cnt_int_value_set(&dev_ctx, 0x0000U);

  /*
   * Set the first address where the programs are written
   * from FSM_START_ADD_L / H.
   */
  lsm6dso_fsm_start_address_set(&dev_ctx, 0x0400);

  /* Set the number of the programs from FSM_PROGRAMS*/
  lsm6dso_fsm_number_of_programs_set(&dev_ctx, 1 );

  /* Enable final state machine */
  lsm6dso_fsm_enable_get(&dev_ctx, &fsm_enable);
  fsm_enable.fsm_enable_a.fsm1_en    = PROPERTY_ENABLE ;
  lsm6dso_fsm_enable_set(&dev_ctx, &fsm_enable);

  /* Set Finite State Machine data rate */
  lsm6dso_fsm_data_rate_set(&dev_ctx, LSM6DSO_ODR_FSM_26Hz);

  /* Write Programs from FSM_START_ADD_L / H */
  fsm_addr = 0x0400;

  /* wakeup */
  lsm6dso_ln_pg_write(&dev_ctx, fsm_addr, (uint8_t*)lsm6so_prg_wakeup,
                      sizeof(lsm6so_prg_wakeup));
  fsm_addr += sizeof(lsm6so_prg_wakeup);

 /*
  * End Finite State Machine configuration
  */

  /* Set Output Data Rate */
  lsm6dso_xl_data_rate_set(&dev_ctx, LSM6DSO_XL_ODR_104Hz);
  lsm6dso_gy_data_rate_set(&dev_ctx, LSM6DSO_GY_ODR_OFF);

  /* Main loop */
  while(1)
  {
    /* Read interrupt source registers in polling mode (no int) */
    lsm6dso_all_sources_get(&dev_ctx, &status);

    if(status.fsm_status_a.is_fsm1){
        sprintf((char*)tx_buffer, "wakeup detected\r\n");
        tx_com(tx_buffer, strlen((char const*)tx_buffer));
    }
    HAL_Delay(20);
  }
}

/*
 * @brief  Write generic device register (platform dependent)
 *
 * @param  handle    customizable argument. In this examples is used in
 *                   order to select the correct sensor bus handler.
 * @param  reg       register to write
 * @param  bufp      pointer to data to write in register reg
 * @param  len       number of consecutive register to write
 *
 */
static int32_t platform_write(void *handle, uint8_t reg, uint8_t *bufp,
                              uint16_t len)
{
    HAL_I2C_Mem_Write(handle, LSM6DSO_I2C_ADD_H, reg,
                      I2C_MEMADD_SIZE_8BIT, bufp, len, 1000);
  return 0;
}

/*
 * @brief  Read generic device register (platform dependent)
 *
 * @param  handle    customizable argument. In this examples is used in
 *                   order to select the correct sensor bus handler.
 * @param  reg       register to read
 * @param  bufp      pointer to buffer that store the data read
 * @param  len       number of consecutive register to read
 *
 */
static int32_t platform_read(void *handle, uint8_t reg, uint8_t *bufp,
                             uint16_t len)
{
    HAL_I2C_Mem_Read(handle, LSM6DSO_I2C_ADD_H, reg,
                     I2C_MEMADD_SIZE_8BIT, bufp, len, 1000);
  return 0;
}

/*
 * @brief  Write generic device register (platform dependent)
 *
 * @param  tx_buffer     buffer to trasmit
 * @param  len           number of byte to send
 *
 */
static void tx_com(uint8_t *tx_buffer, uint16_t len)
{
  HAL_UART_Transmit(&huart2, tx_buffer, len, 1000);
}


